language: python
# ===== Linux ======
python:
  - 3.6
  - 3.7
  - 3.8

before_script: &PREPARE_ENV
    - mkdir test
    - cp LICENSE test/
script: &RUN
  - python -m mkzftree2 -a xz test out

matrix:
  include:      
    # ======= OSX ========
    - &OSX
      name: "Python 3.6"
      os: osx
      language: shell
      env: PYTHON_VERSION=3.6.8
      addons:
        homebrew:
          update: true
          packages:
            - python3
            - pyenv
      before_install:
        - python3 --version
        - echo 'eval "$(pyenv init -)"' >> ~/.bash_profile 
        - source ~/.bash_profile
        - pyenv install $PYTHON_VERSION
        - pyenv global $PYTHON_VERSION
        - python3 --version
      <<: *PREPARE_ENV
      <<: *RUN
    - <<: *OSX
      env: PYTHON_VERSION=3.7.9
    - <<: *OSX
      env: PYTHON_VERSION=3.8.6
    #  ====== WINDOWS =========
    - &WINDOWS
      name: "Python 3.6"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      env:
        - PYTHON_VERSION=3.6.8
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
      before_install:
        - choco install python --version $PYTHON_VERSION
        - python --version
        - python -m pip install --upgrade pip
      <<: *PREPARE_ENV
      <<: *RUN
    - <<: *WINDOWS
      env:
        - PYTHON_VERSION=3.6.8
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH

    - <<: *WINDOWS
      env:
        - PYTHON_VERSION=3.7.9
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH

    - <<: *WINDOWS
      env:
        - PYTHON_VERSION=3.8.6
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
