language: python
os:
  - linux
  - osx
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build
# # command to install dependencies
# install:
#   - pip install -r requirements.txt
# # command to run tests
before_script:
    - mkdir test
    - cp LICENSE test/
script:
  - python3 -m mkzftree2 -a xz tests out
