language: python
# ===== Linux ======
python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - python -m pip install --upgrade pip
before_script: &PREPARE_ENV
  - python --version
  - pip install -e .[test]
script: &RUN
  - pytest -vs

matrix:
  include:      
    # ======= OSX ========
    - &OSX
      os: osx
      language: shell
      env: PYTHON_VERSION=3.6.8
      addons:
        homebrew:
          packages:
            - python3
            - pyenv
      before_install:
        - python3 --version
        - echo 'eval "$(pyenv init -)"' >> ~/.bash_profile 
        - source ~/.bash_profile
        - pyenv install --list
        - pyenv install $PYTHON_VERSION
        - pyenv global $PYTHON_VERSION
        - python --version
        - python -m pip install --upgrade pip
      <<: *PREPARE_ENV
      <<: *RUN
    - <<: *OSX
      env: PYTHON_VERSION=3.7.5
    - <<: *OSX
      env: PYTHON_VERSION=3.8.0
    #  ====== WINDOWS =========
    - &WINDOWS
      os: windows
      language: shell
      env: PYTHON_VERSION=3.6.8
      before_install:
        - export PATH=/c/Python3${PYTHON_VERSION:2:1}:/c/Python3${PYTHON_VERSION:2:1}/Scripts:$PATH
        - choco install python --version $PYTHON_VERSION
        - python --version
        - python -m pip install --upgrade pip
      <<: *PREPARE_ENV
      <<: *RUN
    - <<: *WINDOWS
      env: PYTHON_VERSION=3.7.9
    - <<: *WINDOWS
      env: PYTHON_VERSION=3.8.6
